#!/bin/zsh

cd /Applications

#download zip
curl http://10.8.9.89/Adobe_SDL_AllApps_Enable_SS_Only_231018_en_US_MACUNIVERSAL.zip --output adobe.zip

unzip /Applications/adobe.zip


sudo installer -pkg /Applications/Adobe_SDL_AllApps_Enable_SS_Only_231018/Build/Adobe_SDL_AllApps_Enable_SS_Only_231018_Install.pkg -target /Applications

#cleanup
rm /Applications/adobe.zip
rm -r /Applications/Adobe_SDL_AllApps_Enable_SS_Only_231018/

exit 0
